apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: pi878dwxm-nodejs
  janus-idp.io/tekton: pi878dwxm-nodejs
  backstage.io/kubernetes-id: pi878dwxm-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pi878dwxm-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
