apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: pi878dwxm-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pi878dwxm-nodejs 
  name: pi878dwxm-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: pi878dwxm-nodejs 
